language: java
jdk:
  - oraclejdk8
sudo: false

services:
  - docker

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - mvn install -DskipTests -Pdefault,docker
  - mvn deploy -DskipTests -Pdocker
  - docker tag marketreaction/workflow:$TRAVIS_BUILD_NUMBER marketreaction/workflow:latest
  - docker push marketreaction/workflow:latest